### ISSUE TITLE
Date type

### ISSUE THREAD

**Issue by dotfelixb** [JuliaDB/PostgreSQL.jl#1]
tried a stmt like this "SELECT now();" but had
ERROR: no method pgtype(Type{OID{1082}})

**Comment by iamed2** [comment]
Dates are currently selectable as text which fixes the specific error you mentioned. Closing this, with more types to come.

(Some background, I lost a bunch of work when my computer died. Then I lost a bunch of work when my computer was lost. Aiming to push more frequently now that the package is a bit more stable and usable.)
