### ISSUE TITLE
move to JuliaDB org?

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaDB/PostgreSQL.jl#13]
Seems like there's a collection of database stuff here: https://github.com/JuliaDB.

cc: @quinnj, @johnmyleswhite, @iamed2

**Comment by johnmyleswhite** [comment]
I'm hopeful that we can make up a coherent plan for JuliaDB at JuliaCon this year.

**Comment by quinnj** [comment]
+1

**Comment by StefanKarpinski** [comment]
Related: https://github.com/quinnj/ODBC.jl/issues/88
